### ISSUE TITLE
Build against system yajl?

### ISSUE THREAD

**Issue by QuLogic** [jeroen/jsonlite#201]
Is this possible? If not, can it be made possible? The readme seem to point to mostly pre-running cmake and maybe a couple bug fixes. But perhaps these changes are too great to unbundle.

**Comment by QuLogic** [comment]
Forgot to mention that this is in the context of [packaging jsonlite in Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1489340) and we have [an existing yajl package](https://apps.fedoraproject.org/packages/yajl) and some small fixes could be applied there though substantial changes might not. ([Some reasoning behind unbundling](https://fedoraproject.org/wiki/Bundled_Libraries).)

**Comment by jeroen** [comment]
No I made a bunch of custom changes to the yajl code, better stick with the bundled version.

**Comment by jeroen** [comment]
@QuLogic can you perhaps help packaging up my [V8 package](https://cran.r-project.org/web/packages/V8/index.html) for Fedora? Users often find this difficult to install because it depends on [`v8-314-devel`](https://apps.fedoraproject.org/packages/v8-314). Being able to just install the `R-v8` package would be really great.

**Comment by QuLogic** [comment]
Would need to at least package `R-curl` first (which may not be far off.)

**Comment by Alessandro-Barbieri** [comment]
Can you submit those custom changes to upstream yajl?

**Comment by jeroen** [comment]
The changes are specific for this package, so no. Also upstream yajl is unmaintained.
