### ISSUE TITLE
asJSON for call and expression classes

### ISSUE THREAD

**Issue by nuest** [jeroen/jsonlite#217]
_Would you welcome `asJSON` methods for objects of class `call` and `expression`?_

Having read #62 and #90, I have not been able to come up with a solution for simply letting the user know how a call or expression looks like in JSON.

For my use case, it would be enough to simply convert them to strings with `deparse`, which I now do outside of the JSON conversion function, which is possible but not as nice and does not handle nesting.

**Comment by jeroen** [comment]
I don't think this is a good idea. Expressions are not *data*, they are an R specific type. It doesn't make  much sense to store them as JSON because they have on representation in other languages. 

I suggest you keep doing what you currently do and deparse expressions into strings if you really want to export the R syntax to JSON. But obviously if you read that back, you will have strings, not expressions.

Note that the `serializeJSON()` function *does* support expressions.
