### ISSUE TITLE
bigint_as_char not working

### ISSUE THREAD

**Issue by richierocks** [jeroen/jsonlite#242]
I have some large integers in a block of JSON that I'd like to store as strings in R. The advice in this [closed issue](https://github.com/jeroen/jsonlite/issues/111) suggests that I should use the `bigint_as_char` argument. It doesn't seem to work.

To reproduce:

```r
jsonlite::fromJSON("123456789012345", bigint_as_char = TRUE)     
## [1] 1.234568e+14
jsonlite:::parse_string("123456789012345", bigint_as_char = TRUE)
## [1] 1.234568e+14
```

**Comment by richierocks** [comment]
I think the problem is this line of code:

https://github.com/jeroen/jsonlite/blob/master/src/parse.c#L58

```c
if(bigint && (val > 9007199254740992 || val < -9007199254740992)){
```

R has a much smaller range of possible integers, from -2147483647 to 2147483647 (`.Machine$integer.max`).

**Comment by jeroen** [comment]
This is the range of whole numbers that can be stored in a double without loss of precision. 

```r
x <- jsonlite::fromJSON("123456789012345", bigint_as_char = TRUE)    
print(x, digits = 20)
```

**Comment by richierocks** [comment]
OK, fair enough. For numbers greater than `2 ^ 53`, I still see the result as numeric.

```r
x <- "1267650600228229401496703205376" # 2 ^ 100
fromJSON(x, bigint_as_char = TRUE)
[1] 1.267651e+30
```

**Comment by jeroen** [comment]
It only works for int64 values that don't fit in a double. It's a terrible hack, I don't recommend using json numbers that cannot be stored in a double if you require such precision. 

The JSON number type is intended for high precision bignums. JSON is intended to be portable and most languages only use integer and double. You will see the same problem with any JSON parser, e.g. JavaScript `JSON.parse()` also parses numbers into doubles, so you will lose precision after 16 digits.

In practice your example is a bit artificial because almost no language would be able to generate JSON values above the int64 range with absolute precision. And if the original value was a double, then it already didn't have that precision to begin with.
