### ISSUE TITLE
base64 error while decoding valid character string

### ISSUE THREAD

**Issue by DatenBergwerker** [jeroen/jsonlite#252]
Hello,
first of all, thanks for the awesome package. It makes dealing with web data in R bearable.

When I want to decode this (exemplary) string which is part of a web token, I get the error " Error in base64 decode". The same string decodes correctly with the base64enc package function. I saw this happening in around 10k other instances of my data. 

```
library(jsonlite)
library(base64enc)

teststr = "eyJleHAiOjE1MTk4Mjg2NzcsInVzZXJfbmFtZSI6IjJjZDY4MjU5LTAxNDItNDg5Yy1iZDYxLTdiOTA2NWM5ODRlYyIsImF1dGhvcml0aWVzIjpbIlVTRVIiXSwianRpIjoiOGFjMWVmOTctOTZhZS00NTUwLWExZDQtNWY1NjlmNzQ0OWJjIiwiY2xpZW50X2lkIjoiYXBvbGxvX2lvc19hcHAiLCJzY29wZSI6WyJBUE9MTE8iXX0"

base64_dec(teststr)
base64decode(teststr)
```

Is this expected behaviour? If so what I am I missing?

Sysinfo:
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.0                         
year           2018                        
month          04                          
day            23                          
svn rev        74626                       
language       R                           
version.string R version 3.5.0 (2018-04-23)
nickname       Joy in Playing

jsonlite version 1.5

**Comment by jeroen** [comment]
The problem is that your data is not valid base64, because the length of a proper base64 string must be a multiple of 4. The remaining space must be filled up by `=` characters. This works:

```r
fixed <- paste0(teststr, "=")
base64_dec(teststr)
```

The jsonlite base64 decoder is a bit more strict than the other one, so it will error instead of just return a best guess.

The real question is, are you sure your input is base64? Note that there is a popular variant of base64 called base64url which does not have this requirement. For example try:

```r
jose::base64url_dec(teststr)
```

But be careful because base64url has 2 different characters in it's alphabet than the original base64.

**Comment by DatenBergwerker** [comment]
Thanks for clearing this up. I did not think to further check the input, after it seemingly worked. I'll look into the base64url question though, since that might be the case.
👍
