### ISSUE TITLE
An argument to ensure the `txt` argument of fromJSON() is true text or true file

### ISSUE THREAD

**Issue by yihui** [jeroen/jsonlite#265]
Currently `fromJSON()` intelligently guesses if the `txt` argument is a string or a file path. There is no way to stop it from guessing. I wish there is an argument to control this behavior, e.g., `fromJSON(fromFile = FALSE)`.

It is possible that there happens to be a file named `[1]` (which is valid JSON) and the user wants to read this file instead of the string `[1]`.

Let me know if you wants a PR. Thanks!

**Comment by yihui** [comment]
FWIW, `RJSONIO::fromJSON()` has an `asText` argument (i.e. a way to stop the reader from guessing).

**Comment by jcheng5** [comment]
For further context, when the input is untrusted (as commonly happens with Shiny and plumber) a malicious attacker can easily provoke jsonlite into reading arbitrary files on disk, which it will then echo a few lines of as part of the error message. This vulnerability was found by a black box pen-tester for one of our customers.

Since this is such a subtle vulnerability, might I suggest separate `fromJSONText` and `fromJSONFile` functions? That way it's harder to miss that these alternatives exist (at least in R environments with autocomplete).

If you agree with this approach I'd be happy to file a PR.

**Comment by yihui** [comment]
Actually I do want simplification and I'm afraid that is more likely to be what most people want (e.g. `[1, 2, 3]` should be read as `c(1, 2, 3)` instead of `list(1, 2, 3)` in R)... If you only export `parseJSON()`, we'd have to call your internal function `jsonlite:::simplify()` if we want to simplify the result, which is clearly not the right thing to do for CRAN packages.

If you want to export a function, I hope it would be `fromJSON_string()` instead.

**Comment by jcheng5** [comment]
I don't have an opinion on simplification vs. not, I'm sure you can't please everyone all the time no matter which way you go...

**Comment by jeroen** [comment]
Added a function `parse_json()` which will only read literal json or actual connection objects, and does not try to guess if a string is actually a URL or file.

Also it does not simplify by default but you can set it to TRUE if you'd like.

Does this work for you @yihui ?

**Comment by yihui** [comment]
Yes! Many thanks! 👍

**Comment by jeroen** [comment]
This is on CRAN now.
