### ISSUE TITLE
Respect numeric precision with 0

### ISSUE THREAD

**Issue by coatless** [jeroen/jsonlite#289]
When the numeric value of `0` is found, the parse does not properly convert it to a double in JSON, c.f.

```r
jsonlite::toJSON(0)
# [0] 
jsonlite::toJSON(0.0)
# [0] 
jsonlite::toJSON(numeric(1))
# [0] 
```

This is even the case with list data:

```r
jsonlite::toJSON(list(0, 0.0, 1.45, 2.1, 3L))
# [[0],[0],[1.45],[2.1],[3]]
```

In order to enforce a double, I have to request it via `always_decimal = TRUE`. c.f. 

```r
jsonlite::toJSON(0, always_decimal = TRUE)
# [0.0] 
```

Is there any reason why the `numeric` type for 0 is being dropped?

Also, could more documentation be added with respect to the new parameters? e.g. `always_decimal` is hidden.

**Comment by jeroen** [comment]
Numbers in json do not have type, see the json spec. There is no such thing as a "double" or "int64" or "short", there are just _numbers_. Hence `0.0` equals `0` for the same reason that in R:

```r
print(0.0)
# 0
```

The `always_decimal` parameter is a bit of a hack, it is not officially supported or documented because it is not part of the json standard. I think it's bad practice to rely on this because you should not expect the json parser on the other end to treat `0` any differently from `0.0`.
