### ISSUE TITLE
Should new class for asJSON method be defined in jsonlite?

### ISSUE THREAD

**Issue by shrektan** [jeroen/jsonlite#327]
A user of DT raises [an issue](https://github.com/rstudio/DT/issues/840), which is due to the missing method of `asJSON()` for `ITime`. The latter is an S3 class defined by the data.table package and is used for storing the time-of-day values.

Adding the below code in jsonlite will resolve the user's issue (I've tested it) but I'm not sure if this is the right way to go.

I mean, should this method be defined in jsonlite or should it be defined in the data.table package (is it possible to do)? 

If defining the method in jsonlite is desired, I can help to file a PR later.

Thanks!

```r
setMethod("asJSON", "ITime", function(x, ...) {
  asJSON(as.character(x), ...)
})
```

**Comment by jeroen** [comment]
It is not possible for other packages to define `asJSON` methods. We only support converting the standard data types. But in this case it seems easy enough to add a method to jsonlite, if `ITime` is a common data type. However I would recommend:

```r
setMethod("asJSON", "ITime", function(x, ...) {
  asJSON(as.POSIXct(x), ...)
})
```

Because that way the user can use all the data formatting options implemented in `asJSON.POSIXct`

**Comment by shrektan** [comment]
Unfortunately, we can't use `as.POSIXct()` because `ITime` only store the time-of-day values, i.e., "12:00:00". It doesn't contain the "Date" part.
