### ISSUE TITLE
allow bigint_as_char=T use with stream_in?

### ISSUE THREAD

**Issue by bezkonserwantow** [jeroen/jsonlite#405]
Using stream_in to import externally provided JSONL data results in imprecise number values where faithfulness is important:

```
example = file()
cat("{\"id\": 1413617112501850121, \"id2\": 1573334441849667584}\n", file = example)
stream_in(example)
#expected output:   id 1413617112501850121  id2 1573334441849667584
#actual output:     id 1413617112501850112  id2 1573334441849667584
```

I found the explanation for this, can tinker out a few solutions, and don’t want to bother you longer than a minute. One way to solve this I hoped for first, after some googling, was for the stream_in function to handle the bigint_as_char argument (pass it to parseJSON). Would such a change work and be OK, or is this functionality too irksome or ugly of a hack?

**Comment by jeroen** [comment]
I strongly recommend against using int64 in json data because it is not portable. In most languages/implementations, such as JavaScript, the numbers will be converted to a double, so you lose the precision. 

The `bigint_as_char` is really a hack, if you need exact int64 values then JSON probably isn't the best choice...

**Comment by bezkonserwantow** [comment]
I appreciate the answer and will close the issue. Thanks!
